//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisTest.ReportService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://report.xys.org/", ConfigurationName="ReportService.ReportStatusSoap")]
    internal interface ReportStatusSoap {
        
        // CODEGEN: 命名空间 http://report.xys.org/ 的元素名称 HelloResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://report.xys.org/Hello", ReplyAction="*")]
        LisTest.ReportService.HelloResponse Hello(LisTest.ReportService.HelloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://report.xys.org/Hello", ReplyAction="*")]
        System.Threading.Tasks.Task<LisTest.ReportService.HelloResponse> HelloAsync(LisTest.ReportService.HelloRequest request);
        
        // CODEGEN: 命名空间 http://report.xys.org/ 的元素名称 param 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://report.xys.org/UpdateLabApplyInfo", ReplyAction="*")]
        LisTest.ReportService.UpdateLabApplyInfoResponse UpdateLabApplyInfo(LisTest.ReportService.UpdateLabApplyInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://report.xys.org/UpdateLabApplyInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<LisTest.ReportService.UpdateLabApplyInfoResponse> UpdateLabApplyInfoAsync(LisTest.ReportService.UpdateLabApplyInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class HelloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Hello", Namespace="http://report.xys.org/", Order=0)]
        public LisTest.ReportService.HelloRequestBody Body;
        
        public HelloRequest() {
        }
        
        public HelloRequest(LisTest.ReportService.HelloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class HelloRequestBody {
        
        public HelloRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class HelloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloResponse", Namespace="http://report.xys.org/", Order=0)]
        public LisTest.ReportService.HelloResponseBody Body;
        
        public HelloResponse() {
        }
        
        public HelloResponse(LisTest.ReportService.HelloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://report.xys.org/")]
    internal partial class HelloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloResult;
        
        public HelloResponseBody() {
        }
        
        public HelloResponseBody(string HelloResult) {
            this.HelloResult = HelloResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class UpdateLabApplyInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateLabApplyInfo", Namespace="http://report.xys.org/", Order=0)]
        public LisTest.ReportService.UpdateLabApplyInfoRequestBody Body;
        
        public UpdateLabApplyInfoRequest() {
        }
        
        public UpdateLabApplyInfoRequest(LisTest.ReportService.UpdateLabApplyInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://report.xys.org/")]
    internal partial class UpdateLabApplyInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string param;
        
        public UpdateLabApplyInfoRequestBody() {
        }
        
        public UpdateLabApplyInfoRequestBody(string param) {
            this.param = param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class UpdateLabApplyInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateLabApplyInfoResponse", Namespace="http://report.xys.org/", Order=0)]
        public LisTest.ReportService.UpdateLabApplyInfoResponseBody Body;
        
        public UpdateLabApplyInfoResponse() {
        }
        
        public UpdateLabApplyInfoResponse(LisTest.ReportService.UpdateLabApplyInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class UpdateLabApplyInfoResponseBody {
        
        public UpdateLabApplyInfoResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface ReportStatusSoapChannel : LisTest.ReportService.ReportStatusSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class ReportStatusSoapClient : System.ServiceModel.ClientBase<LisTest.ReportService.ReportStatusSoap>, LisTest.ReportService.ReportStatusSoap {
        
        public ReportStatusSoapClient() {
        }
        
        public ReportStatusSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportStatusSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportStatusSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportStatusSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LisTest.ReportService.HelloResponse LisTest.ReportService.ReportStatusSoap.Hello(LisTest.ReportService.HelloRequest request) {
            return base.Channel.Hello(request);
        }
        
        public string Hello() {
            LisTest.ReportService.HelloRequest inValue = new LisTest.ReportService.HelloRequest();
            inValue.Body = new LisTest.ReportService.HelloRequestBody();
            LisTest.ReportService.HelloResponse retVal = ((LisTest.ReportService.ReportStatusSoap)(this)).Hello(inValue);
            return retVal.Body.HelloResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LisTest.ReportService.HelloResponse> LisTest.ReportService.ReportStatusSoap.HelloAsync(LisTest.ReportService.HelloRequest request) {
            return base.Channel.HelloAsync(request);
        }
        
        public System.Threading.Tasks.Task<LisTest.ReportService.HelloResponse> HelloAsync() {
            LisTest.ReportService.HelloRequest inValue = new LisTest.ReportService.HelloRequest();
            inValue.Body = new LisTest.ReportService.HelloRequestBody();
            return ((LisTest.ReportService.ReportStatusSoap)(this)).HelloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LisTest.ReportService.UpdateLabApplyInfoResponse LisTest.ReportService.ReportStatusSoap.UpdateLabApplyInfo(LisTest.ReportService.UpdateLabApplyInfoRequest request) {
            return base.Channel.UpdateLabApplyInfo(request);
        }
        
        public void UpdateLabApplyInfo(string param) {
            LisTest.ReportService.UpdateLabApplyInfoRequest inValue = new LisTest.ReportService.UpdateLabApplyInfoRequest();
            inValue.Body = new LisTest.ReportService.UpdateLabApplyInfoRequestBody();
            inValue.Body.param = param;
            LisTest.ReportService.UpdateLabApplyInfoResponse retVal = ((LisTest.ReportService.ReportStatusSoap)(this)).UpdateLabApplyInfo(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LisTest.ReportService.UpdateLabApplyInfoResponse> LisTest.ReportService.ReportStatusSoap.UpdateLabApplyInfoAsync(LisTest.ReportService.UpdateLabApplyInfoRequest request) {
            return base.Channel.UpdateLabApplyInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<LisTest.ReportService.UpdateLabApplyInfoResponse> UpdateLabApplyInfoAsync(string param) {
            LisTest.ReportService.UpdateLabApplyInfoRequest inValue = new LisTest.ReportService.UpdateLabApplyInfoRequest();
            inValue.Body = new LisTest.ReportService.UpdateLabApplyInfoRequestBody();
            inValue.Body.param = param;
            return ((LisTest.ReportService.ReportStatusSoap)(this)).UpdateLabApplyInfoAsync(inValue);
        }
    }
}
