//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisTest.FRService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://fr.xys.org/", ConfigurationName="FRService.LabPDFSoap")]
    public interface LabPDFSoap {
        
        // CODEGEN: 命名空间 http://fr.xys.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://fr.xys.org/HelloWorld", ReplyAction="*")]
        LisTest.FRService.HelloWorldResponse HelloWorld(LisTest.FRService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fr.xys.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<LisTest.FRService.HelloWorldResponse> HelloWorldAsync(LisTest.FRService.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://fr.xys.org/ 的元素名称 bytes 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://fr.xys.org/PrintPDF", ReplyAction="*")]
        LisTest.FRService.PrintPDFResponse PrintPDF(LisTest.FRService.PrintPDFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fr.xys.org/PrintPDF", ReplyAction="*")]
        System.Threading.Tasks.Task<LisTest.FRService.PrintPDFResponse> PrintPDFAsync(LisTest.FRService.PrintPDFRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://fr.xys.org/", Order=0)]
        public LisTest.FRService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(LisTest.FRService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://fr.xys.org/", Order=0)]
        public LisTest.FRService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(LisTest.FRService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fr.xys.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrintPDFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrintPDF", Namespace="http://fr.xys.org/", Order=0)]
        public LisTest.FRService.PrintPDFRequestBody Body;
        
        public PrintPDFRequest() {
        }
        
        public PrintPDFRequest(LisTest.FRService.PrintPDFRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fr.xys.org/")]
    public partial class PrintPDFRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] bytes;
        
        public PrintPDFRequestBody() {
        }
        
        public PrintPDFRequestBody(byte[] bytes) {
            this.bytes = bytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrintPDFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrintPDFResponse", Namespace="http://fr.xys.org/", Order=0)]
        public LisTest.FRService.PrintPDFResponseBody Body;
        
        public PrintPDFResponse() {
        }
        
        public PrintPDFResponse(LisTest.FRService.PrintPDFResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PrintPDFResponseBody {
        
        public PrintPDFResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LabPDFSoapChannel : LisTest.FRService.LabPDFSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LabPDFSoapClient : System.ServiceModel.ClientBase<LisTest.FRService.LabPDFSoap>, LisTest.FRService.LabPDFSoap {
        
        public LabPDFSoapClient() {
        }
        
        public LabPDFSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LabPDFSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LabPDFSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LabPDFSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LisTest.FRService.HelloWorldResponse LisTest.FRService.LabPDFSoap.HelloWorld(LisTest.FRService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            LisTest.FRService.HelloWorldRequest inValue = new LisTest.FRService.HelloWorldRequest();
            inValue.Body = new LisTest.FRService.HelloWorldRequestBody();
            LisTest.FRService.HelloWorldResponse retVal = ((LisTest.FRService.LabPDFSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LisTest.FRService.HelloWorldResponse> LisTest.FRService.LabPDFSoap.HelloWorldAsync(LisTest.FRService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<LisTest.FRService.HelloWorldResponse> HelloWorldAsync() {
            LisTest.FRService.HelloWorldRequest inValue = new LisTest.FRService.HelloWorldRequest();
            inValue.Body = new LisTest.FRService.HelloWorldRequestBody();
            return ((LisTest.FRService.LabPDFSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LisTest.FRService.PrintPDFResponse LisTest.FRService.LabPDFSoap.PrintPDF(LisTest.FRService.PrintPDFRequest request) {
            return base.Channel.PrintPDF(request);
        }
        
        public void PrintPDF(byte[] bytes) {
            LisTest.FRService.PrintPDFRequest inValue = new LisTest.FRService.PrintPDFRequest();
            inValue.Body = new LisTest.FRService.PrintPDFRequestBody();
            inValue.Body.bytes = bytes;
            LisTest.FRService.PrintPDFResponse retVal = ((LisTest.FRService.LabPDFSoap)(this)).PrintPDF(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LisTest.FRService.PrintPDFResponse> LisTest.FRService.LabPDFSoap.PrintPDFAsync(LisTest.FRService.PrintPDFRequest request) {
            return base.Channel.PrintPDFAsync(request);
        }
        
        public System.Threading.Tasks.Task<LisTest.FRService.PrintPDFResponse> PrintPDFAsync(byte[] bytes) {
            LisTest.FRService.PrintPDFRequest inValue = new LisTest.FRService.PrintPDFRequest();
            inValue.Body = new LisTest.FRService.PrintPDFRequestBody();
            inValue.Body.bytes = bytes;
            return ((LisTest.FRService.LabPDFSoap)(this)).PrintPDFAsync(inValue);
        }
    }
}
