//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XYS.Report.WS.FRService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LabReport", Namespace="http://fr.xys.org/")]
    [System.SerializableAttribute()]
    internal partial class LabReport : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private XYS.Report.WS.FRService.ReportPK ReportPKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private XYS.Report.WS.FRService.InfoElement InfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private XYS.Report.WS.FRService.ItemElement[] ItemListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private XYS.Report.WS.FRService.ImageElement[] ImageListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal XYS.Report.WS.FRService.ReportPK ReportPK {
            get {
                return this.ReportPKField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportPKField, value) != true)) {
                    this.ReportPKField = value;
                    this.RaisePropertyChanged("ReportPK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        internal XYS.Report.WS.FRService.InfoElement Info {
            get {
                return this.InfoField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoField, value) != true)) {
                    this.InfoField = value;
                    this.RaisePropertyChanged("Info");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        internal XYS.Report.WS.FRService.ItemElement[] ItemList {
            get {
                return this.ItemListField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemListField, value) != true)) {
                    this.ItemListField = value;
                    this.RaisePropertyChanged("ItemList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        internal XYS.Report.WS.FRService.ImageElement[] ImageList {
            get {
                return this.ImageListField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageListField, value) != true)) {
                    this.ImageListField = value;
                    this.RaisePropertyChanged("ImageList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportPK", Namespace="http://fr.xys.org/")]
    [System.SerializableAttribute()]
    internal partial class ReportPK : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int SectionNoField;
        
        private int TestTypeNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SampleNoField;
        
        private System.DateTime ReceiveDateField;
        
        private bool ConfiguredField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal int SectionNo {
            get {
                return this.SectionNoField;
            }
            set {
                if ((this.SectionNoField.Equals(value) != true)) {
                    this.SectionNoField = value;
                    this.RaisePropertyChanged("SectionNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal int TestTypeNo {
            get {
                return this.TestTypeNoField;
            }
            set {
                if ((this.TestTypeNoField.Equals(value) != true)) {
                    this.TestTypeNoField = value;
                    this.RaisePropertyChanged("TestTypeNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        internal string SampleNo {
            get {
                return this.SampleNoField;
            }
            set {
                if ((object.ReferenceEquals(this.SampleNoField, value) != true)) {
                    this.SampleNoField = value;
                    this.RaisePropertyChanged("SampleNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        internal System.DateTime ReceiveDate {
            get {
                return this.ReceiveDateField;
            }
            set {
                if ((this.ReceiveDateField.Equals(value) != true)) {
                    this.ReceiveDateField = value;
                    this.RaisePropertyChanged("ReceiveDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        internal bool Configured {
            get {
                return this.ConfiguredField;
            }
            set {
                if ((this.ConfiguredField.Equals(value) != true)) {
                    this.ConfiguredField = value;
                    this.RaisePropertyChanged("Configured");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoElement", Namespace="http://fr.xys.org/")]
    [System.SerializableAttribute()]
    internal partial class InfoElement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatientNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgeStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatientIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClinicNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CIDField;
        
        private int VisitTimesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BedNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeptNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DoctorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClinicalDiagnosisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExplanationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerialNoField;
        
        private int SectionNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SampleNoField;
        
        private int SampleTypeNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SampleTypeNameField;
        
        private System.DateTime ReceiveTimeField;
        
        private System.DateTime CollectTimeField;
        
        private System.DateTime InceptTimeField;
        
        private System.DateTime TestTimeField;
        
        private System.DateTime CheckTimeField;
        
        private System.DateTime FinalTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TechnicianField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CheckerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MemoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportContentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string PatientName {
            get {
                return this.PatientNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PatientNameField, value) != true)) {
                    this.PatientNameField = value;
                    this.RaisePropertyChanged("PatientName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        internal string GenderName {
            get {
                return this.GenderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderNameField, value) != true)) {
                    this.GenderNameField = value;
                    this.RaisePropertyChanged("GenderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        internal string AgeStr {
            get {
                return this.AgeStrField;
            }
            set {
                if ((object.ReferenceEquals(this.AgeStrField, value) != true)) {
                    this.AgeStrField = value;
                    this.RaisePropertyChanged("AgeStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        internal string PatientID {
            get {
                return this.PatientIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PatientIDField, value) != true)) {
                    this.PatientIDField = value;
                    this.RaisePropertyChanged("PatientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        internal string ClinicName {
            get {
                return this.ClinicNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClinicNameField, value) != true)) {
                    this.ClinicNameField = value;
                    this.RaisePropertyChanged("ClinicName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        internal string ReportID {
            get {
                return this.ReportIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportIDField, value) != true)) {
                    this.ReportIDField = value;
                    this.RaisePropertyChanged("ReportID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        internal string CID {
            get {
                return this.CIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CIDField, value) != true)) {
                    this.CIDField = value;
                    this.RaisePropertyChanged("CID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        internal int VisitTimes {
            get {
                return this.VisitTimesField;
            }
            set {
                if ((this.VisitTimesField.Equals(value) != true)) {
                    this.VisitTimesField = value;
                    this.RaisePropertyChanged("VisitTimes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        internal string BedNo {
            get {
                return this.BedNoField;
            }
            set {
                if ((object.ReferenceEquals(this.BedNoField, value) != true)) {
                    this.BedNoField = value;
                    this.RaisePropertyChanged("BedNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        internal string DeptName {
            get {
                return this.DeptNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DeptNameField, value) != true)) {
                    this.DeptNameField = value;
                    this.RaisePropertyChanged("DeptName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        internal string Doctor {
            get {
                return this.DoctorField;
            }
            set {
                if ((object.ReferenceEquals(this.DoctorField, value) != true)) {
                    this.DoctorField = value;
                    this.RaisePropertyChanged("Doctor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        internal string ClinicalDiagnosis {
            get {
                return this.ClinicalDiagnosisField;
            }
            set {
                if ((object.ReferenceEquals(this.ClinicalDiagnosisField, value) != true)) {
                    this.ClinicalDiagnosisField = value;
                    this.RaisePropertyChanged("ClinicalDiagnosis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        internal string Explanation {
            get {
                return this.ExplanationField;
            }
            set {
                if ((object.ReferenceEquals(this.ExplanationField, value) != true)) {
                    this.ExplanationField = value;
                    this.RaisePropertyChanged("Explanation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        internal string SerialNo {
            get {
                return this.SerialNoField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialNoField, value) != true)) {
                    this.SerialNoField = value;
                    this.RaisePropertyChanged("SerialNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        internal int SectionNo {
            get {
                return this.SectionNoField;
            }
            set {
                if ((this.SectionNoField.Equals(value) != true)) {
                    this.SectionNoField = value;
                    this.RaisePropertyChanged("SectionNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        internal string SampleNo {
            get {
                return this.SampleNoField;
            }
            set {
                if ((object.ReferenceEquals(this.SampleNoField, value) != true)) {
                    this.SampleNoField = value;
                    this.RaisePropertyChanged("SampleNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        internal int SampleTypeNo {
            get {
                return this.SampleTypeNoField;
            }
            set {
                if ((this.SampleTypeNoField.Equals(value) != true)) {
                    this.SampleTypeNoField = value;
                    this.RaisePropertyChanged("SampleTypeNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        internal string SampleTypeName {
            get {
                return this.SampleTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SampleTypeNameField, value) != true)) {
                    this.SampleTypeNameField = value;
                    this.RaisePropertyChanged("SampleTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        internal System.DateTime ReceiveTime {
            get {
                return this.ReceiveTimeField;
            }
            set {
                if ((this.ReceiveTimeField.Equals(value) != true)) {
                    this.ReceiveTimeField = value;
                    this.RaisePropertyChanged("ReceiveTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        internal System.DateTime CollectTime {
            get {
                return this.CollectTimeField;
            }
            set {
                if ((this.CollectTimeField.Equals(value) != true)) {
                    this.CollectTimeField = value;
                    this.RaisePropertyChanged("CollectTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        internal System.DateTime InceptTime {
            get {
                return this.InceptTimeField;
            }
            set {
                if ((this.InceptTimeField.Equals(value) != true)) {
                    this.InceptTimeField = value;
                    this.RaisePropertyChanged("InceptTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=21)]
        internal System.DateTime TestTime {
            get {
                return this.TestTimeField;
            }
            set {
                if ((this.TestTimeField.Equals(value) != true)) {
                    this.TestTimeField = value;
                    this.RaisePropertyChanged("TestTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=22)]
        internal System.DateTime CheckTime {
            get {
                return this.CheckTimeField;
            }
            set {
                if ((this.CheckTimeField.Equals(value) != true)) {
                    this.CheckTimeField = value;
                    this.RaisePropertyChanged("CheckTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=23)]
        internal System.DateTime FinalTime {
            get {
                return this.FinalTimeField;
            }
            set {
                if ((this.FinalTimeField.Equals(value) != true)) {
                    this.FinalTimeField = value;
                    this.RaisePropertyChanged("FinalTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        internal string Technician {
            get {
                return this.TechnicianField;
            }
            set {
                if ((object.ReferenceEquals(this.TechnicianField, value) != true)) {
                    this.TechnicianField = value;
                    this.RaisePropertyChanged("Technician");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        internal string Checker {
            get {
                return this.CheckerField;
            }
            set {
                if ((object.ReferenceEquals(this.CheckerField, value) != true)) {
                    this.CheckerField = value;
                    this.RaisePropertyChanged("Checker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        internal string Memo {
            get {
                return this.MemoField;
            }
            set {
                if ((object.ReferenceEquals(this.MemoField, value) != true)) {
                    this.MemoField = value;
                    this.RaisePropertyChanged("Memo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        internal string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        internal string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        internal string ReportContent {
            get {
                return this.ReportContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportContentField, value) != true)) {
                    this.ReportContentField = value;
                    this.RaisePropertyChanged("ReportContent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemElement", Namespace="http://fr.xys.org/")]
    [System.SerializableAttribute()]
    internal partial class ItemElement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportIDField;
        
        private int ItemNoField;
        
        private int SuperNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ENameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RefRangeField;
        
        private int DispOrderField;
        
        private int SecretGradeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string ReportID {
            get {
                return this.ReportIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportIDField, value) != true)) {
                    this.ReportIDField = value;
                    this.RaisePropertyChanged("ReportID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        internal int ItemNo {
            get {
                return this.ItemNoField;
            }
            set {
                if ((this.ItemNoField.Equals(value) != true)) {
                    this.ItemNoField = value;
                    this.RaisePropertyChanged("ItemNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        internal int SuperNo {
            get {
                return this.SuperNoField;
            }
            set {
                if ((this.SuperNoField.Equals(value) != true)) {
                    this.SuperNoField = value;
                    this.RaisePropertyChanged("SuperNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        internal string CName {
            get {
                return this.CNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CNameField, value) != true)) {
                    this.CNameField = value;
                    this.RaisePropertyChanged("CName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        internal string EName {
            get {
                return this.ENameField;
            }
            set {
                if ((object.ReferenceEquals(this.ENameField, value) != true)) {
                    this.ENameField = value;
                    this.RaisePropertyChanged("EName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        internal string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        internal string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        internal string Unit {
            get {
                return this.UnitField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitField, value) != true)) {
                    this.UnitField = value;
                    this.RaisePropertyChanged("Unit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        internal string RefRange {
            get {
                return this.RefRangeField;
            }
            set {
                if ((object.ReferenceEquals(this.RefRangeField, value) != true)) {
                    this.RefRangeField = value;
                    this.RaisePropertyChanged("RefRange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        internal int DispOrder {
            get {
                return this.DispOrderField;
            }
            set {
                if ((this.DispOrderField.Equals(value) != true)) {
                    this.DispOrderField = value;
                    this.RaisePropertyChanged("DispOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        internal int SecretGrade {
            get {
                return this.SecretGradeField;
            }
            set {
                if ((this.SecretGradeField.Equals(value) != true)) {
                    this.SecretGradeField = value;
                    this.RaisePropertyChanged("SecretGrade");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImageElement", Namespace="http://fr.xys.org/")]
    [System.SerializableAttribute()]
    internal partial class ImageElement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string ReportID {
            get {
                return this.ReportIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportIDField, value) != true)) {
                    this.ReportIDField = value;
                    this.RaisePropertyChanged("ReportID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        internal string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        internal string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://fr.xys.org/", ConfigurationName="FRService.LisPDFSoap")]
    internal interface LisPDFSoap {
        
        // CODEGEN: 命名空间 http://fr.xys.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://fr.xys.org/HelloWorld", ReplyAction="*")]
        XYS.Report.WS.FRService.HelloWorldResponse HelloWorld(XYS.Report.WS.FRService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fr.xys.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<XYS.Report.WS.FRService.HelloWorldResponse> HelloWorldAsync(XYS.Report.WS.FRService.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://fr.xys.org/ 的元素名称 report 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://fr.xys.org/PrintPDF", ReplyAction="*")]
        XYS.Report.WS.FRService.PrintPDFResponse PrintPDF(XYS.Report.WS.FRService.PrintPDFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fr.xys.org/PrintPDF", ReplyAction="*")]
        System.Threading.Tasks.Task<XYS.Report.WS.FRService.PrintPDFResponse> PrintPDFAsync(XYS.Report.WS.FRService.PrintPDFRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://fr.xys.org/", Order=0)]
        public XYS.Report.WS.FRService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(XYS.Report.WS.FRService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://fr.xys.org/", Order=0)]
        public XYS.Report.WS.FRService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(XYS.Report.WS.FRService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fr.xys.org/")]
    internal partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class PrintPDFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrintPDF", Namespace="http://fr.xys.org/", Order=0)]
        public XYS.Report.WS.FRService.PrintPDFRequestBody Body;
        
        public PrintPDFRequest() {
        }
        
        public PrintPDFRequest(XYS.Report.WS.FRService.PrintPDFRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fr.xys.org/")]
    internal partial class PrintPDFRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public XYS.Report.WS.FRService.LabReport report;
        
        public PrintPDFRequestBody() {
        }
        
        public PrintPDFRequestBody(XYS.Report.WS.FRService.LabReport report) {
            this.report = report;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class PrintPDFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrintPDFResponse", Namespace="http://fr.xys.org/", Order=0)]
        public XYS.Report.WS.FRService.PrintPDFResponseBody Body;
        
        public PrintPDFResponse() {
        }
        
        public PrintPDFResponse(XYS.Report.WS.FRService.PrintPDFResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fr.xys.org/")]
    internal partial class PrintPDFResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool PrintPDFResult;
        
        public PrintPDFResponseBody() {
        }
        
        public PrintPDFResponseBody(bool PrintPDFResult) {
            this.PrintPDFResult = PrintPDFResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface LisPDFSoapChannel : XYS.Report.WS.FRService.LisPDFSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class LisPDFSoapClient : System.ServiceModel.ClientBase<XYS.Report.WS.FRService.LisPDFSoap>, XYS.Report.WS.FRService.LisPDFSoap {
        
        public LisPDFSoapClient() {
        }
        
        public LisPDFSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LisPDFSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LisPDFSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LisPDFSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XYS.Report.WS.FRService.HelloWorldResponse XYS.Report.WS.FRService.LisPDFSoap.HelloWorld(XYS.Report.WS.FRService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            XYS.Report.WS.FRService.HelloWorldRequest inValue = new XYS.Report.WS.FRService.HelloWorldRequest();
            inValue.Body = new XYS.Report.WS.FRService.HelloWorldRequestBody();
            XYS.Report.WS.FRService.HelloWorldResponse retVal = ((XYS.Report.WS.FRService.LisPDFSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XYS.Report.WS.FRService.HelloWorldResponse> XYS.Report.WS.FRService.LisPDFSoap.HelloWorldAsync(XYS.Report.WS.FRService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<XYS.Report.WS.FRService.HelloWorldResponse> HelloWorldAsync() {
            XYS.Report.WS.FRService.HelloWorldRequest inValue = new XYS.Report.WS.FRService.HelloWorldRequest();
            inValue.Body = new XYS.Report.WS.FRService.HelloWorldRequestBody();
            return ((XYS.Report.WS.FRService.LisPDFSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XYS.Report.WS.FRService.PrintPDFResponse XYS.Report.WS.FRService.LisPDFSoap.PrintPDF(XYS.Report.WS.FRService.PrintPDFRequest request) {
            return base.Channel.PrintPDF(request);
        }
        
        public bool PrintPDF(XYS.Report.WS.FRService.LabReport report) {
            XYS.Report.WS.FRService.PrintPDFRequest inValue = new XYS.Report.WS.FRService.PrintPDFRequest();
            inValue.Body = new XYS.Report.WS.FRService.PrintPDFRequestBody();
            inValue.Body.report = report;
            XYS.Report.WS.FRService.PrintPDFResponse retVal = ((XYS.Report.WS.FRService.LisPDFSoap)(this)).PrintPDF(inValue);
            return retVal.Body.PrintPDFResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XYS.Report.WS.FRService.PrintPDFResponse> XYS.Report.WS.FRService.LisPDFSoap.PrintPDFAsync(XYS.Report.WS.FRService.PrintPDFRequest request) {
            return base.Channel.PrintPDFAsync(request);
        }
        
        public System.Threading.Tasks.Task<XYS.Report.WS.FRService.PrintPDFResponse> PrintPDFAsync(XYS.Report.WS.FRService.LabReport report) {
            XYS.Report.WS.FRService.PrintPDFRequest inValue = new XYS.Report.WS.FRService.PrintPDFRequest();
            inValue.Body = new XYS.Report.WS.FRService.PrintPDFRequestBody();
            inValue.Body.report = report;
            return ((XYS.Report.WS.FRService.LisPDFSoap)(this)).PrintPDFAsync(inValue);
        }
    }
}
