//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XYS.ReportWS.FRService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://fr.xys.org/", ConfigurationName="FRService.PDFSoap")]
    internal interface PDFSoap {
        
        // CODEGEN: 命名空间 http://fr.xys.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://fr.xys.org/HelloWorld", ReplyAction="*")]
        XYS.ReportWS.FRService.HelloWorldResponse HelloWorld(XYS.ReportWS.FRService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fr.xys.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<XYS.ReportWS.FRService.HelloWorldResponse> HelloWorldAsync(XYS.ReportWS.FRService.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://fr.xys.org/ 的元素名称 bytes 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://fr.xys.org/LabPDF", ReplyAction="*")]
        XYS.ReportWS.FRService.LabPDFResponse LabPDF(XYS.ReportWS.FRService.LabPDFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fr.xys.org/LabPDF", ReplyAction="*")]
        System.Threading.Tasks.Task<XYS.ReportWS.FRService.LabPDFResponse> LabPDFAsync(XYS.ReportWS.FRService.LabPDFRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://fr.xys.org/", Order=0)]
        public XYS.ReportWS.FRService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(XYS.ReportWS.FRService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://fr.xys.org/", Order=0)]
        public XYS.ReportWS.FRService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(XYS.ReportWS.FRService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fr.xys.org/")]
    internal partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class LabPDFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LabPDF", Namespace="http://fr.xys.org/", Order=0)]
        public XYS.ReportWS.FRService.LabPDFRequestBody Body;
        
        public LabPDFRequest() {
        }
        
        public LabPDFRequest(XYS.ReportWS.FRService.LabPDFRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fr.xys.org/")]
    internal partial class LabPDFRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] bytes;
        
        public LabPDFRequestBody() {
        }
        
        public LabPDFRequestBody(byte[] bytes) {
            this.bytes = bytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class LabPDFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LabPDFResponse", Namespace="http://fr.xys.org/", Order=0)]
        public XYS.ReportWS.FRService.LabPDFResponseBody Body;
        
        public LabPDFResponse() {
        }
        
        public LabPDFResponse(XYS.ReportWS.FRService.LabPDFResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class LabPDFResponseBody {
        
        public LabPDFResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface PDFSoapChannel : XYS.ReportWS.FRService.PDFSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class PDFSoapClient : System.ServiceModel.ClientBase<XYS.ReportWS.FRService.PDFSoap>, XYS.ReportWS.FRService.PDFSoap {
        
        public PDFSoapClient() {
        }
        
        public PDFSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PDFSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PDFSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PDFSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XYS.ReportWS.FRService.HelloWorldResponse XYS.ReportWS.FRService.PDFSoap.HelloWorld(XYS.ReportWS.FRService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            XYS.ReportWS.FRService.HelloWorldRequest inValue = new XYS.ReportWS.FRService.HelloWorldRequest();
            inValue.Body = new XYS.ReportWS.FRService.HelloWorldRequestBody();
            XYS.ReportWS.FRService.HelloWorldResponse retVal = ((XYS.ReportWS.FRService.PDFSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XYS.ReportWS.FRService.HelloWorldResponse> XYS.ReportWS.FRService.PDFSoap.HelloWorldAsync(XYS.ReportWS.FRService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<XYS.ReportWS.FRService.HelloWorldResponse> HelloWorldAsync() {
            XYS.ReportWS.FRService.HelloWorldRequest inValue = new XYS.ReportWS.FRService.HelloWorldRequest();
            inValue.Body = new XYS.ReportWS.FRService.HelloWorldRequestBody();
            return ((XYS.ReportWS.FRService.PDFSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XYS.ReportWS.FRService.LabPDFResponse XYS.ReportWS.FRService.PDFSoap.LabPDF(XYS.ReportWS.FRService.LabPDFRequest request) {
            return base.Channel.LabPDF(request);
        }
        
        public void LabPDF(byte[] bytes) {
            XYS.ReportWS.FRService.LabPDFRequest inValue = new XYS.ReportWS.FRService.LabPDFRequest();
            inValue.Body = new XYS.ReportWS.FRService.LabPDFRequestBody();
            inValue.Body.bytes = bytes;
            XYS.ReportWS.FRService.LabPDFResponse retVal = ((XYS.ReportWS.FRService.PDFSoap)(this)).LabPDF(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XYS.ReportWS.FRService.LabPDFResponse> XYS.ReportWS.FRService.PDFSoap.LabPDFAsync(XYS.ReportWS.FRService.LabPDFRequest request) {
            return base.Channel.LabPDFAsync(request);
        }
        
        public System.Threading.Tasks.Task<XYS.ReportWS.FRService.LabPDFResponse> LabPDFAsync(byte[] bytes) {
            XYS.ReportWS.FRService.LabPDFRequest inValue = new XYS.ReportWS.FRService.LabPDFRequest();
            inValue.Body = new XYS.ReportWS.FRService.LabPDFRequestBody();
            inValue.Body.bytes = bytes;
            return ((XYS.ReportWS.FRService.PDFSoap)(this)).LabPDFAsync(inValue);
        }
    }
}
