//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XYS.ReportWS.FRService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://fr.xys.org/", ConfigurationName="FRService.LabPDFSoap")]
    internal interface LabPDFSoap {
        
        // CODEGEN: 命名空间 http://fr.xys.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://fr.xys.org/HelloWorld", ReplyAction="*")]
        XYS.ReportWS.FRService.HelloWorldResponse HelloWorld(XYS.ReportWS.FRService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fr.xys.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<XYS.ReportWS.FRService.HelloWorldResponse> HelloWorldAsync(XYS.ReportWS.FRService.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://fr.xys.org/ 的元素名称 bytes 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://fr.xys.org/PrintPDF", ReplyAction="*")]
        XYS.ReportWS.FRService.PrintPDFResponse PrintPDF(XYS.ReportWS.FRService.PrintPDFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fr.xys.org/PrintPDF", ReplyAction="*")]
        System.Threading.Tasks.Task<XYS.ReportWS.FRService.PrintPDFResponse> PrintPDFAsync(XYS.ReportWS.FRService.PrintPDFRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://fr.xys.org/", Order=0)]
        public XYS.ReportWS.FRService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(XYS.ReportWS.FRService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://fr.xys.org/", Order=0)]
        public XYS.ReportWS.FRService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(XYS.ReportWS.FRService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fr.xys.org/")]
    internal partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class PrintPDFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrintPDF", Namespace="http://fr.xys.org/", Order=0)]
        public XYS.ReportWS.FRService.PrintPDFRequestBody Body;
        
        public PrintPDFRequest() {
        }
        
        public PrintPDFRequest(XYS.ReportWS.FRService.PrintPDFRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fr.xys.org/")]
    internal partial class PrintPDFRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] bytes;
        
        public PrintPDFRequestBody() {
        }
        
        public PrintPDFRequestBody(byte[] bytes) {
            this.bytes = bytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class PrintPDFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrintPDFResponse", Namespace="http://fr.xys.org/", Order=0)]
        public XYS.ReportWS.FRService.PrintPDFResponseBody Body;
        
        public PrintPDFResponse() {
        }
        
        public PrintPDFResponse(XYS.ReportWS.FRService.PrintPDFResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class PrintPDFResponseBody {
        
        public PrintPDFResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface LabPDFSoapChannel : XYS.ReportWS.FRService.LabPDFSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class LabPDFSoapClient : System.ServiceModel.ClientBase<XYS.ReportWS.FRService.LabPDFSoap>, XYS.ReportWS.FRService.LabPDFSoap {
        
        public LabPDFSoapClient() {
        }
        
        public LabPDFSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LabPDFSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LabPDFSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LabPDFSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XYS.ReportWS.FRService.HelloWorldResponse XYS.ReportWS.FRService.LabPDFSoap.HelloWorld(XYS.ReportWS.FRService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            XYS.ReportWS.FRService.HelloWorldRequest inValue = new XYS.ReportWS.FRService.HelloWorldRequest();
            inValue.Body = new XYS.ReportWS.FRService.HelloWorldRequestBody();
            XYS.ReportWS.FRService.HelloWorldResponse retVal = ((XYS.ReportWS.FRService.LabPDFSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XYS.ReportWS.FRService.HelloWorldResponse> XYS.ReportWS.FRService.LabPDFSoap.HelloWorldAsync(XYS.ReportWS.FRService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<XYS.ReportWS.FRService.HelloWorldResponse> HelloWorldAsync() {
            XYS.ReportWS.FRService.HelloWorldRequest inValue = new XYS.ReportWS.FRService.HelloWorldRequest();
            inValue.Body = new XYS.ReportWS.FRService.HelloWorldRequestBody();
            return ((XYS.ReportWS.FRService.LabPDFSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XYS.ReportWS.FRService.PrintPDFResponse XYS.ReportWS.FRService.LabPDFSoap.PrintPDF(XYS.ReportWS.FRService.PrintPDFRequest request) {
            return base.Channel.PrintPDF(request);
        }
        
        public void PrintPDF(byte[] bytes) {
            XYS.ReportWS.FRService.PrintPDFRequest inValue = new XYS.ReportWS.FRService.PrintPDFRequest();
            inValue.Body = new XYS.ReportWS.FRService.PrintPDFRequestBody();
            inValue.Body.bytes = bytes;
            XYS.ReportWS.FRService.PrintPDFResponse retVal = ((XYS.ReportWS.FRService.LabPDFSoap)(this)).PrintPDF(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XYS.ReportWS.FRService.PrintPDFResponse> XYS.ReportWS.FRService.LabPDFSoap.PrintPDFAsync(XYS.ReportWS.FRService.PrintPDFRequest request) {
            return base.Channel.PrintPDFAsync(request);
        }
        
        public System.Threading.Tasks.Task<XYS.ReportWS.FRService.PrintPDFResponse> PrintPDFAsync(byte[] bytes) {
            XYS.ReportWS.FRService.PrintPDFRequest inValue = new XYS.ReportWS.FRService.PrintPDFRequest();
            inValue.Body = new XYS.ReportWS.FRService.PrintPDFRequestBody();
            inValue.Body.bytes = bytes;
            return ((XYS.ReportWS.FRService.LabPDFSoap)(this)).PrintPDFAsync(inValue);
        }
    }
}
